version: "3.8"
services:
  php:
    image: php:7.4-cli-alpine
    volumes:
      - ./:/app:rw
    working_dir: /app

  composer:
    image: composer:2.3.7
    volumes:
      - ./:/app
    working_dir: /app